In [1]:
import numpy as np
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt

In [2]:
x = np.linspace(0, 2*np.pi,100)
y = np.cos(x)

In [3]:
fig, ax = plt.subplots()
ax.plot(x, y, color = 'green')

In [4]:
fig = plt.figure(figsize=(10,8))
ax = fig.add_subplot(111)

In [5]:
points = [1,4,6,7,9,4,2,4,5,6,5,3,2,1,2,4,6,7]

In [6]:
ax.plot(points)
fig.savefig('graph.png')


Can we extend this?

Add a title for the graph

Add x axis label

Add y axis label

Plot more than one line


Can you create different types of charts?

In [7]:
z = [1,4,6,7,9,4,2,4,5,6,5,3,2,1,2,4,6,7]
p = np.random.randint(50, size= (18))

plt.title('Lecture 21/02/2022')
plt.xlabel('Numbers')
plt.ylabel('Other Numbers')
plt.plot(points)

In [8]:
x = [7, 14, 21, 28, 35, 42, 49]
y = [5, 12, 19, 21, 31, 27, 35]
z = [3, 5, 11, 20, 15, 29, 31]

plt.plot(x, y, 'g', label='Line y')

plt.plot(x, z, 'r', label='Line z')

plt.title('Lecture 21/02/2022')
plt.xlabel('Numbers')
plt.ylabel('Other Numbers')
plt.legend()


In [9]:
# create dataset
height = [3, 12, 5, 18, 45]
bars = ('A', 'B', 'C', 'D', 'E')
x_pos = np.arange(len(bars))
 
# Create bars and choose color
plt.bar(x_pos, height, color = (0.5,0.1,0.5,0.6))
 
# Add title and axis names
plt.title('My title')
plt.xlabel('categories')
plt.ylabel('values')
 
# Create names on the x axis
plt.xticks(x_pos, bars)
 
# Show graph
plt.show()

C:\Users\glorimer\AppData\Local\Temp/ipykernel_13384/4182215432.py:18: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()


In [10]:
import numpy as np

# Define data values in array
arr = np.array([[7, 5, 3], [14, 12, 5], [21, 19, 11],
                [28, 21, 20], [35, 31, 15], [42, 27, 29],
                [49, 35, 31]])

print(np.shape(arr), type(arr), arr, sep='\n')

(7, 3)
<class 'numpy.ndarray'>
[[ 7  5  3]
 [14 12  5]
 [21 19 11]
 [28 21 20]
 [35 31 15]
 [42 27 29]
 [49 35 31]]
